### ISSUE TITLE
Amazing Driver

### ISSUE THREAD

**Issue by kureikain** [rgv151/rethinkdb.nim#1]
This is just super cool. An attempt that fail miserable with Erlang https://github.com/kureikain/relang/commit/7c7e55476474dbea5c016284b63704ceca9e433f :(

**Comment by rgv151** [comment]
thx em

**Comment by rgv151** [comment]
the hardest part is comming, filter by expression haha

**Comment by kureikain** [comment]
Actually the logic is not that hard I think. The hardest part is how to represent it in host language in an elegrant way. It may be easier with chain-able language. For Erlang, hereis what I come up with (sadly).

```Erlang
relang:r(Connection, [[{db, ["test"]}, {table, ["t4"]}, {filter, fun(X) ->
 relang:row(X, <<"age">>,  [{eq, 30}])
end}).
```

**Comment by rgv151** [comment]
Actually expresssion is working now:
```nim
r.table("user").filter(r.row["score"] > 90).run()
```

My current problem is working with anonymous functions

**Comment by rgv151** [comment]
btw, my syntax looks simpler than yours lol

**Comment by kureikain** [comment]
> My current problem is working with anonymous functions

That's what I meant.

```
relang:r(Connection, [[{db, ["test"]}, {table, ["t4"]}, {filter, fun(X) ->
 relang:row(X, <<"age">>,  [{eq, 30}])
end}).
```

^ my anoymous function, notice `func(X) ->`

The expression is even uglier

```
# working
relang:r(Connection, [[{db, ["test"]}, {table, ["t4"]}, {filter, [{<<"age">>, 30}).
```
But my expression is only support matching, for other thing, users has to use anonymous function.

NIM seems support operator overloading. It is a very powerful language if it does that.

**Comment by kureikain** [comment]
It's fun when we come to this point, writing low level driver. How cool is that? :D even cooler when knowing someone else whom we know also doing the same :D.

**Comment by rgv151** [comment]
I'm very happy when I saw you create relang project ;)

yes Nim is awesome, that's why I don't pick Go or Rust. In orther view, your anonymous functions is just another way to write an expresssion. What Python did is parse anonymous function's source code, and generate RQL AST from it. I dont know how to do that w/ Nim yet (if possiblle), cuz Nim ins't scripting language like Python or JS

**Comment by kureikain** [comment]
>  In orther view, your anonymous functions is just another way to write an expresssion

They are real function. They are executed and the returned value is passed to filter to construct array [69,[[2,[var_number]], the_returned_value]

> What Python did is parse anonymous function's source code, and generate RQL AST from it

I don't know Python but I think you are wrong here. The function has to be executed. Without executing you don't know the output.

Take this Pseudo code:

```
r.table("users").filter{ |user|
   user["age"].eq 100
   89   
}.run(conn)
```

The return value is 89, and filter REQL is: `[69,[[2,[var_number_here]],89]`. 

Take this pseduo tcode:

```
r.table("users").filter{ |user|
   a_result_from_other_reql = r.table("stats").filter{|user| user["age"].gt(89)}.first["username"]

   user_name_pattern = crazy_function_here(a_result_from_other_reql)
   user["name"].match(   user_name_pattern)
}.run(conn)
```

so how do you know how to contruct REQL for `match` without executing them? Not counting about closure vars, so you have to execute,not?

That's my current approach. I actually execute the anonoymous function, and grab the result. Then pass to filter, and call it a day :D. Not elegrant and maybe naieve but it works haha.

My struggling is that I cannot overload operator and do infix operator so that I can do `and` `or` in an easy way and readable.

```Erlang
relang:r(C1, 
  [{db, [<<"test">>]}, 
   {table, [<<"tv_shows">>]}, 
   {filter, fun(X) ->    
      //Find the first USER in a table
      [First | Rest] = relang:r(C1, [{db [<<"test">>]}, {table, [<<"tv_shows">>]}, {first}])
      //do some craazy stuff with that user
      K = do_crazy_suff(First)
      M = "^" ++ L
     relang:row(X, [{match, [{<<"name">>, <<"M>>}]}]) 
   end}
 ]
).
```

**Comment by rgv151** [comment]
you right, em! I made a mistake while reading Python code.
Here is my implementation:
```nim
r.table("users").map((x: RqlQuery) => x["age"] >= 30).run()
```
Nim's lambda is not flexible like Python. And the compiler still has a bug with type inference for lambda.
So I can't implement more complex form `of anonymous functions` yet

**Comment by kureikain** [comment]
Yeah, let's improve our drivers throught time. omg, cannot believe we write our own driver.

Let's submit your driver to RethinkDB docs? https://github.com/rethinkdb/docs/blob/master/1-get-started/drivers/index.md

**Comment by rgv151** [comment]
it does not complete yet em
