### ISSUE TITLE
Not working on nim 1.4.8

### ISSUE THREAD

**Issue by Chiggy-Playz** [rgv151/rethinkdb.nim#15]
I get errors when I try to run the following code : 
```nim
import rethinkdb

var r = newRethinkclient([address = "localhost",] [port = Port(28015),], [db = "hlna"])
```

Error : `/home/chiggy/.nimble/pkgs/rethinkdb-0.2.4/rethinkdb.nim(1, 15) Error: cannot open file: private/datum`

How can I fix this?

**Comment by ba0f3** [comment]
it works for me on dev version. I bumped it to 0.2.5, please update and try again. thank you!

**Comment by Chiggy-Playz** [comment]
I reinstalled `rethinkdb` from nimble and still same issue
![image](https://user-images.githubusercontent.com/49774426/130118253-639447ea-f827-453a-8e40-5a0d1bcba6a7.png)

**Comment by ba0f3** [comment]
try to install it again, latest version is 0.2.6

**Comment by Chiggy-Playz** [comment]
0.2.6 solved the private/datum issue, but I have a different issue now. I just tried to run the example code, and got the following error. Could it be because examples are outdated?
![image](https://user-images.githubusercontent.com/49774426/130122702-39c74603-7ccd-4034-8ebb-2961147d920b.png)

**Comment by ba0f3** [comment]
You got syntax error, remove brackets, they mean optional

**Comment by Chiggy-Playz** [comment]
Thank you. Can you update the examples to work with nim 1.4.8 please? or guide me on how to get data and insert it?

**Comment by ba0f3** [comment]
Check out `tests` folder for demo
