### ISSUE TITLE
Async mode

### ISSUE THREAD

**Issue by karantin2020** [rgv151/rethinkdb.nim#3]
When compile without `threads` option there is an error:
```
.nimble/pkgs/rethinkdb-0.1.4/private/connection.nim(135, 5) Error:
internal error: expr(skTemplate); unknown symbol
No stack traceback available
```
I have this error when compile test_lambdas.nim

But when use `threads=on` everything is allright.
What is that?

**Comment by karantin2020** [comment]
Sorry. It was my mistake. I changed connection.nim. That's why error was

**Comment by rgv151** [comment]
good to here that :+1:
