### ISSUE TITLE
rethinkdb.row() usage: "Expected 2 arguments but found 1."

### ISSUE THREAD

**Issue by niv** [rgv151/rethinkdb.nim#5]
Hi!

Great work on the driver. Learning a lot about nim just reading the sources.

I've run into a small issue using it though:

```nim
  let q = g_rethinkDB.table("tbl").
    getAll([identifier], "tbl_id").
    update(&*{
      "aryKey": row("aryKey").append("test")
    })

  echo waitFor q.run()
```

That code would append a value to the array at aryKey.

Running this code returns "Expected 2 arguments but found 1." from rethinkdb. Is this a bug, or am I misusing row()?

Thanks!

**Comment by rgv151** [comment]
The driver does not support this complex query yet. I will implement it soon

**Comment by niv** [comment]
Ah, good to hear I just missed that part. Thank you for your quick response!

**Comment by rgv151** [comment]
I found that append proc didnt work as expected, Will try to figure out later tonight

**Comment by rgv151** [comment]
Your code should be rewrite as bellow, notes:
1. dont use `&*` operator for complex queries
2. r.row should be use along with `[]` not `()` (sorry I forgot how to call them in English)
```nim
let q = g_rethinkDB.table("tbl").
    getAll([identifier], "tbl_id").
    update({
      "aryKey": r.row["aryKey"].append("test")
    })

echo waitFor q.run()

**Comment by niv** [comment]
Thanks! That code works with the latest from git. Two questions if I may ask:

- what's wrong with using &*? What is it for? It's converting it to JSON? It was the only way I could make things work (I took it from the tests dir).

- Unfortunately, some other code "broke" and I can't figure out why:

```nim
filter( (q: RqlQuery) => q["field"] == someLocalString )
```

now results in "type mismatch: got (empty, string)" - I guess q[anything] doesn't resolve to a type?

It's all very new to me. Sorry for bugging you, I appreciate you looking at this.

**Comment by rgv151** [comment]
* `&*` is a shorthand (macro) to convert any kind of data (object, array,...) into a `MutableDatum`, and then the driver converts it into JSON.
* Previously, Nim's type inferrence and lambas aren't good. Lambdas supporting for this driver is just a workaround, smth will works and smth ain't.
I think these headcache will gone w/ newly Nim's release. it's time for refactoring :v:
